// Generated by Themis code scan. Do not edit manually.
// Source: src/App.tsx

const path = require('path');
const {
  listExportNames,
  buildModuleContract,
  readExportValue,
  normalizeBehaviorValue,
  normalizeRouteResult,
  createRequestFromSpec,
  assertSourceFreshness,
  runComponentInteractionContract,
  runComponentBehaviorFlowContract,
  runHookInteractionContract
} = require("@vitronai/themis/contract-runtime");

const SOURCE_PATH = "src/App.tsx";
const SOURCE_IMPORT = "../../src/App.tsx";
const SOURCE_FILE = path.resolve(__dirname, "../../src/App.tsx");
const SOURCE_HASH = "7b6493e72bf9b0b9109b9e6e75036765a1486637";
const REGENERATE_COMMAND = "npx themis generate src/App.tsx";
const SCANNED_EXPORTS = [
  "default"
];
const EXPECTED_EXPORT_CONTRACTS = {
  "default": {
    "kind": "unknown",
    "arity": null,
    "prototypeKeys": null
  }
};
const PROJECT_PROVIDER_IMPORT = null;
const PROJECT_PROVIDER_INDEXES = [];
const PROJECT_PROVIDER_PRESETS = [];
const NEXT_APP_CASES = [];
const NEXT_ROUTE_CASES = [];
const COMPONENT_CASES = [];
const HOOK_CASES = [];
const ROUTE_CASES = [];
const SERVICE_CASES = [];

function loadModuleExports() {
  assertSourceFreshness(SOURCE_FILE, SOURCE_HASH, SOURCE_PATH, REGENERATE_COMMAND);
  const resolved = require.resolve(SOURCE_IMPORT);
  delete require.cache[resolved];
  return require(SOURCE_IMPORT);
}

function applyProjectProviderMocks(exportName, scenarioName) {
  if (!PROJECT_PROVIDER_IMPORT || PROJECT_PROVIDER_INDEXES.length === 0) {
    return;
  }

  const loaded = require(PROJECT_PROVIDER_IMPORT);
  const providers = Array.isArray(loaded)
    ? loaded
    : Array.isArray(loaded && loaded.providers)
      ? loaded.providers
      : loaded
        ? [loaded]
        : [];

  for (const providerIndex of PROJECT_PROVIDER_INDEXES) {
    const provider = providers[providerIndex];
    if (!provider || typeof provider.applyMocks !== 'function') {
      continue;
    }

    provider.applyMocks({
      sourceFile: SOURCE_FILE,
      sourcePath: SOURCE_PATH,
      exportName,
      scenario: scenarioName,
      mock: typeof mock === 'function' ? mock : null,
      fn: typeof fn === 'function' ? fn : null,
      mockFetch: typeof mockFetch === 'function' ? mockFetch : null,
      resetFetchMocks: typeof resetFetchMocks === 'function' ? resetFetchMocks : null,
      restoreFetch: typeof restoreFetch === 'function' ? restoreFetch : null,
      useFakeTimers: typeof useFakeTimers === 'function' ? useFakeTimers : null,
      useRealTimers: typeof useRealTimers === 'function' ? useRealTimers : null,
      advanceTimersByTime: typeof advanceTimersByTime === 'function' ? advanceTimersByTime : null,
      runAllTimers: typeof runAllTimers === 'function' ? runAllTimers : null,
      flushMicrotasks: typeof flushMicrotasks === 'function' ? flushMicrotasks : null
    });
  }
}

function applyProjectProviderRender(element, exportName, scenarioName) {
  let current = applyProjectProviderPresets(element);

  if (!PROJECT_PROVIDER_IMPORT) {
    return current;
  }

  const loaded = require(PROJECT_PROVIDER_IMPORT);
  const providers = Array.isArray(loaded)
    ? loaded
    : Array.isArray(loaded && loaded.providers)
      ? loaded.providers
      : loaded
        ? [loaded]
        : [];

  for (const providerIndex of PROJECT_PROVIDER_INDEXES) {
    const provider = providers[providerIndex];
    if (!provider || typeof provider.wrapRender !== 'function') {
      continue;
    }

    const nextValue = provider.wrapRender({
      sourceFile: SOURCE_FILE,
      sourcePath: SOURCE_PATH,
      exportName,
      scenario: scenarioName,
      element: current,
      withProviderShell,
      withReactRouter(elementValue, config) {
        return withReactRouter(elementValue, config);
      },
      withNextNavigation(elementValue, config) {
        return withNextNavigation(elementValue, config);
      },
      withAuthSession(elementValue, config) {
        return withAuthSession(elementValue, config);
      },
      withReactQuery(elementValue, config) {
        return withReactQuery(elementValue, config);
      },
      withZustandStore(elementValue, config) {
        return withZustandStore(elementValue, config);
      },
      withReduxStore(elementValue, config) {
        return withReduxStore(elementValue, config);
      }
    });

    if (nextValue !== undefined) {
      current = nextValue;
    }
  }

  return current;
}

function applyProjectProviderPresets(element) {
  let current = element;

  for (const preset of PROJECT_PROVIDER_PRESETS) {
    if (preset.router) {
      current = withReactRouter(current, preset.router);
    }
    if (preset.nextNavigation) {
      current = withNextNavigation(current, preset.nextNavigation);
    }
    if (preset.auth) {
      current = withAuthSession(current, preset.auth);
    }
    if (preset.reactQuery) {
      current = withReactQuery(current, preset.reactQuery);
    }
    if (preset.zustand) {
      current = withZustandStore(current, preset.zustand);
    }
    if (preset.redux) {
      current = withReduxStore(current, preset.redux);
    }
  }

  return current;
}

function withProviderShell(type, element, attributes = {}) {
  return {
    $$typeof: 'react.test.element',
    type,
    key: null,
    props: {
      role: attributes.role || 'group',
      ...attributes,
      children: element
    }
  };
}

function withReactRouter(element, config = {}) {
  return withProviderShell('themis-router-provider', element, {
    role: 'navigation',
    'data-themis-provider': 'router',
    'data-route-path': typeof config.path === 'string' ? config.path : '/',
    'data-route-params': serializeProviderData(config.params || {}),
    'data-route-search': serializeProviderData(config.search || {}),
    'data-route-state': serializeProviderData(config.state || {}),
    'data-route-history': serializeProviderData(config.history || []),
    'data-route-name': typeof config.name === 'string' ? config.name : ''
  });
}

function withReactQuery(element, config = {}) {
  return withProviderShell('themis-react-query-provider', element, {
    'data-themis-provider': 'react-query',
    'data-query-client': typeof config.clientName === 'string' ? config.clientName : 'themis-query-client',
    'data-query-state': serializeProviderData(config.state || {}),
    'data-query-cache': serializeProviderData(config.cache || {}),
    'data-query-status': typeof config.status === 'string' ? config.status : 'success',
    'data-query-fetch-status': typeof config.fetchStatus === 'string' ? config.fetchStatus : 'idle',
    'data-query-queries': serializeProviderData(config.queries || [])
  });
}

function withNextNavigation(element, config = {}) {
  return withProviderShell('themis-next-navigation-provider', element, {
    'data-themis-provider': 'next-navigation',
    'data-next-pathname': typeof config.pathname === 'string' ? config.pathname : '/',
    'data-next-params': serializeProviderData(config.params || {}),
    'data-next-search-params': serializeProviderData(config.searchParams || {}),
    'data-next-segment': typeof config.segment === 'string' ? config.segment : '',
    'data-next-locale': typeof config.locale === 'string' ? config.locale : ''
  });
}

function withAuthSession(element, config = {}) {
  return withProviderShell('themis-auth-provider', element, {
    'data-themis-provider': 'auth',
    'data-auth-user': typeof config.user === 'string' ? config.user : 'anonymous',
    'data-auth-session': serializeProviderData(config.session || {}),
    'data-auth-state': typeof config.state === 'string' ? config.state : 'authenticated',
    'data-auth-roles': serializeProviderData(config.roles || []),
    'data-auth-permissions': serializeProviderData(config.permissions || [])
  });
}

function withZustandStore(element, config = {}) {
  return withProviderShell('themis-zustand-provider', element, {
    'data-themis-provider': 'zustand',
    'data-store-name': typeof config.name === 'string' ? config.name : 'zustand-store',
    'data-store-state': serializeProviderData(config.state || {}),
    'data-store-selectors': serializeProviderData(config.selectors || []),
    'data-store-actions': serializeProviderData(config.actions || [])
  });
}

function withReduxStore(element, config = {}) {
  return withProviderShell('themis-redux-provider', element, {
    'data-themis-provider': 'redux',
    'data-redux-slice': typeof config.slice === 'string' ? config.slice : 'root',
    'data-redux-state': serializeProviderData(config.state || {}),
    'data-redux-actions': serializeProviderData(config.actions || []),
    'data-redux-selectors': serializeProviderData(config.selectors || [])
  });
}

function serializeProviderData(value) {
  if (value === undefined) {
    return '';
  }
  return JSON.stringify(normalizeBehaviorValue(value));
}

function assertExpectedRuntimeContract(runtime) {
  expect(typeof runtime).toBe('object');
  expect(runtime === null).toBe(false);

  const expectedNames = Object.keys(EXPECTED_EXPORT_CONTRACTS).sort();
  if (expectedNames.length > 0) {
    expect(Object.keys(runtime).sort()).toEqual(expectedNames);
  }

  for (const [exportName, expected] of Object.entries(EXPECTED_EXPORT_CONTRACTS)) {
    const actual = runtime[exportName];
    expect(Boolean(actual)).toBe(true);

    if (expected.kind && expected.kind !== 'unknown') {
      expect(actual.kind).toBe(expected.kind);
    }

    if (typeof expected.arity === 'number' && (actual.kind === 'function' || actual.kind === 'class')) {
      expect(actual.arity).toBe(expected.arity);
    }

    if (Array.isArray(expected.prototypeKeys) && actual.kind === 'class') {
      expect(actual.prototypeKeys).toEqual(expected.prototypeKeys);
    }
  }
}

function assertNormalizedRenderContract(rendered) {
  const normalized = normalizeBehaviorValue(rendered);
  expect(normalized !== undefined && normalized !== null).toBe(true);

  if (Array.isArray(normalized)) {
    expect(normalized.length >= 0).toBe(true);
    return;
  }

  if (typeof normalized === 'object') {
    if (normalized.kind === 'element') {
      expect(Boolean(normalized.type)).toBe(true);
      expect(typeof normalized.props).toBe('object');
      return;
    }

    expect(Object.keys(normalized).length >= 0).toBe(true);
    return;
  }

  expect(['string', 'number', 'boolean'].includes(typeof normalized)).toBe(true);
}

function assertDomContractShape(contract) {
  expect(typeof contract).toBe('object');
  expect(contract === null).toBe(false);
  expect(Array.isArray(contract.nodes)).toBe(true);
  expect(Array.isArray(contract.roles)).toBe(true);
  expect(typeof contract.textContent).toBe('string');
}

function countPlannedSteps(plan) {
  if (!Array.isArray(plan)) {
    return 0;
  }

  return plan.reduce((total, step) => {
    const repeat = step && typeof step === 'object' ? Number(step.repeat || 1) : 1;
    return total + Math.max(1, Number.isFinite(repeat) ? repeat : 1);
  }, 0);
}

function assertComponentInteractionContractShape(contract, plan) {
  assertNormalizedRenderContract(contract.rendered);
  assertDomContractShape(contract.dom);
  expect(Array.isArray(contract.interactions)).toBe(true);

  if (countPlannedSteps(plan) > 0) {
    expect(contract.interactions.length > 0).toBe(true);
  }

  for (const entry of contract.interactions) {
    expect(typeof entry.label).toBe('string');
    expect(entry.label.length > 0).toBe(true);
    assertDomContractShape(entry.beforeDom);
    assertDomContractShape(entry.afterDom);
  }
}

function assertFlowContractShape(flow, plan) {
  assertDomContractShape(flow.dom);
  expect(Array.isArray(flow.steps)).toBe(true);
  expect(flow.steps.length).toBe(Array.isArray(plan) ? plan.length : 0);

  for (let index = 0; index < flow.steps.length; index += 1) {
    const step = flow.steps[index];
    const expected = Array.isArray(plan) ? plan[index] || {} : {};
    expect(typeof step.label).toBe('string');

    if (step.skipped) {
      continue;
    }

    assertDomContractShape(step.beforeDom);
    assertDomContractShape(step.immediateDom);
    assertDomContractShape(step.settledDom);

    if (expected.expected && typeof expected.expected.immediateTextIncludes === 'string') {
      expect(step.immediateDom.textContent).toContain(expected.expected.immediateTextIncludes);
    }

    if (expected.expected && typeof expected.expected.beforeTextIncludes === 'string') {
      expect(step.beforeDom.textContent).toContain(expected.expected.beforeTextIncludes);
    }

    if (expected.expected && typeof expected.expected.settledTextIncludes === 'string') {
      expect(step.settledDom.textContent).toContain(expected.expected.settledTextIncludes);
    }

    if (expected.expected && typeof expected.expected.textExcludes === 'string') {
      expect(step.settledDom.textContent.includes(expected.expected.textExcludes)).toBe(false);
    }

    if (
      expected.expected
      && expected.expected.attributes
      && typeof expected.expected.attributes === 'object'
      && !Array.isArray(expected.expected.attributes)
    ) {
      const matchesAttributes = [step.immediateDom, step.settledDom].some((dom) => {
        const nodes = dom && Array.isArray(dom.nodes) ? dom.nodes : [];
        return nodes.some((node) => {
          if (!node || node.kind !== 'element' || !node.attributes || typeof node.attributes !== 'object') {
            return false;
          }
          return Object.entries(expected.expected.attributes).every(([key, value]) => JSON.stringify(node.attributes[key]) === JSON.stringify(value));
        });
      });
      expect(matchesAttributes).toBe(true);
    }

    if (expected.expected && expected.expected.rolesInclude !== undefined) {
      const expectedRoles = Array.isArray(expected.expected.rolesInclude)
        ? expected.expected.rolesInclude
        : [expected.expected.rolesInclude];
      const matchesRoles = [step.immediateDom, step.settledDom].some((dom) => {
        const roles = dom && Array.isArray(dom.roles) ? dom.roles : [];
        return expectedRoles.every((role) => roles.some((entry) => entry && entry.role === role));
      });
      expect(matchesRoles).toBe(true);
    }
  }
}

function assertHookResultContract(result) {
  const normalized = normalizeBehaviorValue(result);
  expect(normalized !== undefined).toBe(true);
}

function assertHookInteractionContractShape(contract, plan) {
  expect(Array.isArray(contract.interactions)).toBe(true);

  if (countPlannedSteps(plan) > 0) {
    expect(contract.interactions.length > 0).toBe(true);
  }

  for (const entry of contract.interactions) {
    expect(typeof entry.label).toBe('string');
    expect(entry.label.length > 0).toBe(true);
  }
}

function assertRouteResultContractShape(response) {
  expect(response !== undefined && response !== null).toBe(true);

  if (response && typeof response === 'object' && response.kind === 'response') {
    expect(typeof response.status).toBe('number');
    expect(response.status >= 100).toBe(true);
    expect(response.status < 600).toBe(true);
    expect(typeof response.headers).toBe('object');
  }
}

function assertServiceResultContractShape(result) {
  expect(result !== undefined).toBe(true);
}

describe("generated contract > src/App.tsx", () => {
  test('matches scanned export names', () => {
    const moduleExports = loadModuleExports();
    expect(listExportNames(moduleExports)).toEqual(SCANNED_EXPORTS);
  });

  test('captures runtime export contract', () => {
    const moduleExports = loadModuleExports();
    const runtime = buildModuleContract(moduleExports);
    assertExpectedRuntimeContract(runtime);
  });

  if (NEXT_APP_CASES.length > 0) {
    describe('next app component adapter', () => {
      for (const testCase of NEXT_APP_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, () => {
          applyProjectProviderMocks(testCase.exportName, 'next-app-component');
          const moduleExports = loadModuleExports();
          const component = readExportValue(moduleExports, testCase.exportName);
          const rendered = applyProjectProviderRender(component(testCase.props), testCase.exportName, 'next-app-component');
          assertNormalizedRenderContract(rendered);
        });

        test(testCase.exportName + ' next interaction contract', async () => {
          applyProjectProviderMocks(testCase.exportName, 'next-app-component');
          const interaction = await runComponentInteractionContract(SOURCE_FILE, testCase.exportName, testCase.props, testCase.interactions, {
            wrapRender(element) {
              return applyProjectProviderRender(element, testCase.exportName, 'next-app-component');
            }
          });
          assertComponentInteractionContractShape(interaction, testCase.interactions);
        });

        test(testCase.exportName + ' next dom state contract', async () => {
          applyProjectProviderMocks(testCase.exportName, 'next-app-component');
          const contract = await runComponentInteractionContract(SOURCE_FILE, testCase.exportName, testCase.props, testCase.interactions, {
            wrapRender(element) {
              return applyProjectProviderRender(element, testCase.exportName, 'next-app-component');
            }
          });
          assertDomContractShape(contract.dom);
          if (Array.isArray(testCase.interactions) && testCase.interactions.length > 0) {
            expect(contract.interactions.length > 0).toBe(true);
          }
        });

        if (Array.isArray(testCase.flows) && testCase.flows.length > 0) {
          test(testCase.exportName + ' next behavioral flow contract', async () => {
            applyProjectProviderMocks(testCase.exportName, 'next-app-component');
            const flow = await runComponentBehaviorFlowContract(SOURCE_FILE, testCase.exportName, testCase.props, testCase.flows, {
              wrapRender(element) {
                return applyProjectProviderRender(element, testCase.exportName, 'next-app-component');
              }
            });
            assertFlowContractShape(flow, testCase.flows);
            expect(flow.steps.some((step) => !step.skipped)).toBe(true);
          });
        }
      }
    });
  }

  if (COMPONENT_CASES.length > 0) {
    describe('react component adapter', () => {
      for (const testCase of COMPONENT_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, () => {
          applyProjectProviderMocks(testCase.exportName, 'react-component');
          const moduleExports = loadModuleExports();
          const component = readExportValue(moduleExports, testCase.exportName);
          const rendered = applyProjectProviderRender(component(testCase.props), testCase.exportName, 'react-component');
          assertNormalizedRenderContract(rendered);
        });

        test(testCase.exportName + ' interaction contract', async () => {
          applyProjectProviderMocks(testCase.exportName, 'react-component');
          const interaction = await runComponentInteractionContract(SOURCE_FILE, testCase.exportName, testCase.props, testCase.interactions, {
            wrapRender(element) {
              return applyProjectProviderRender(element, testCase.exportName, 'react-component');
            }
          });
          assertComponentInteractionContractShape(interaction, testCase.interactions);
        });

        test(testCase.exportName + ' dom state contract', async () => {
          applyProjectProviderMocks(testCase.exportName, 'react-component');
          const contract = await runComponentInteractionContract(SOURCE_FILE, testCase.exportName, testCase.props, testCase.interactions, {
            wrapRender(element) {
              return applyProjectProviderRender(element, testCase.exportName, 'react-component');
            }
          });
          assertDomContractShape(contract.dom);
          if (Array.isArray(testCase.interactions) && testCase.interactions.length > 0) {
            expect(contract.interactions.length > 0).toBe(true);
          }
        });

        if (Array.isArray(testCase.flows) && testCase.flows.length > 0) {
          test(testCase.exportName + ' behavioral flow contract', async () => {
            applyProjectProviderMocks(testCase.exportName, 'react-component');
            const flow = await runComponentBehaviorFlowContract(SOURCE_FILE, testCase.exportName, testCase.props, testCase.flows, {
              wrapRender(element) {
                return applyProjectProviderRender(element, testCase.exportName, 'react-component');
              }
            });
            assertFlowContractShape(flow, testCase.flows);
            expect(flow.steps.some((step) => !step.skipped)).toBe(true);
          });
        }
      }
    });
  }

  if (HOOK_CASES.length > 0) {
    describe('react hook adapter', () => {
      for (const testCase of HOOK_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, () => {
          applyProjectProviderMocks(testCase.exportName, 'react-hook');
          const moduleExports = loadModuleExports();
          const hook = readExportValue(moduleExports, testCase.exportName);
          const result = hook(...testCase.args);
          assertHookResultContract(result);
        });

        test(testCase.exportName + ' interaction contract', () => {
          applyProjectProviderMocks(testCase.exportName, 'react-hook');
          const interaction = runHookInteractionContract(SOURCE_FILE, testCase.exportName, testCase.args, testCase.interactions);
          assertHookInteractionContractShape(interaction, testCase.interactions);
        });
      }
    });
  }

  if (NEXT_ROUTE_CASES.length > 0) {
    describe('next route handler adapter', () => {
      for (const testCase of NEXT_ROUTE_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, async () => {
          applyProjectProviderMocks(testCase.exportName, 'next-route-handler');
          const moduleExports = loadModuleExports();
          const handler = readExportValue(moduleExports, testCase.exportName);
          const request = createRequestFromSpec(testCase.request);
          const response = await Promise.resolve(handler(request, testCase.context));
          const normalizedResponse = await normalizeRouteResult(response);
          assertRouteResultContractShape(normalizedResponse);
        });
      }
    });
  }

  if (ROUTE_CASES.length > 0) {
    describe('route handler adapter', () => {
      for (const testCase of ROUTE_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, async () => {
          applyProjectProviderMocks(testCase.exportName, 'route-handler');
          const moduleExports = loadModuleExports();
          const handler = readExportValue(moduleExports, testCase.exportName);
          const request = createRequestFromSpec(testCase.request);
          const response = await Promise.resolve(handler(request, testCase.context));
          const normalizedResponse = await normalizeRouteResult(response);
          assertRouteResultContractShape(normalizedResponse);
        });
      }
    });
  }

  if (SERVICE_CASES.length > 0) {
    describe('node service adapter', () => {
      for (const testCase of SERVICE_CASES) {
        test(testCase.exportName + ' ' + testCase.caseName, async () => {
          applyProjectProviderMocks(testCase.exportName, 'node-service');
          const moduleExports = loadModuleExports();
          const service = readExportValue(moduleExports, testCase.exportName);
          const result = await Promise.resolve(service(...testCase.args));
          assertServiceResultContractShape(normalizeBehaviorValue(result));
        });
      }
    });
  }
});
